services:
  db:
    image: 'postgres:latest'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - 'POSTGRES_DB=coupon_processing_system'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq/data"
    healthcheck:
      timeout: 1200s
      interval: 1200s
      retries: 3
  app:
    image: 'coupon-processing-system'
    build:
      context: .
    ports:
      - '8080:8080' # Substitua pela porta em que sua aplicação está ouvindo
    depends_on:
      - db
      - rabbitmq
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coupon_processing_system'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=admin'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'RABBITMQ_USERNAME=guest'
      - 'RABBITMQ_PASSWORD=guest'
volumes:
  rabbitmq_data:
  postgres_data:
